version: "3"
services:
  mediator:
    image: canacred/aries-mediator
    hostname: mediator
    restart: unless-stopped
    environment:
      - ACAPY_ENDPOINT=[http://bpa.canacred.net:8080/,ws://bpa.canacred.net:8080]
      - ACAPY_WALLET_STORAGE_CONFIG={"url":"db:5432","wallet_scheme":"DatabasePerWallet"}
      - ACAPY_WALLET_STORAGE_CREDS={"account":"development","password":"development","admin_account":"development","admin_password":"development"}
      - ACAPY_WALLET_KEY=testing
    volumes:
      - ./wait-for-it:/home/indy/wait-for-it:z
    command: >
      sh -c "./wait-for-it/wait-for-it.sh db:5432 -s -t 60 -- aca-py start --auto-provision --arg-file ./configs/start.yml"
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: postgres:9.5
    hostname: db
    restart: always
    #    ports: # Uncomment to access postgres outside of containers
    #      - "5432:5432"
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    networks:
      - mediator-network

#Docker Networks
networks:
  mediator-network:
    driver: bridge
